Prototype of Nix integration and solc picking
This pretty much works fine!

I can run dapp in a clean Ubuntu Docker, and it will commence installing
Nix, setting up the DappHub Nix channel, and then reinstalling dapp
via Nix.

It's kind of weird though that you would first download the dapp source
code and install it, and then it would immediately reinstall itself in a
different place using Nix.

So I'm not sure, maybe there should be a separate easy install script,
instead of the check in the main dapp program.

diff --git a/libexec/dapp/dapp b/libexec/dapp/dapp
--- a/libexec/dapp/dapp
+++ b/libexec/dapp/dapp
@@ -4,6 +4,28 @@ export DAPP_SRC=${DAPP_SRC-src}
 export DAPP_LIB=${DAPP_LIB-lib}
 export DAPP_OUT=${DAPP_OUT-out}
 
+function have() { command -v "$1" >/dev/null 2>&1 ; }
+
+for dep in bc curl git node solc ethabi ethrun seth jshon; do
+  if ! have $dep; then missing+=($dep); fi
+done
+
+if [ ${#missing[@]} -gt 0 ]; then
+  echo >&2 "${0##*/}: missing dependencies"
+  echo >&2
+  cat <<-EOF
+If you want to install missing dependencies by hand,
+then answer no to the following and install the following:
+
+    ${missing[@]}
+
+But we recommend that you let Dapp manage its own tools,
+and answer yes to the following.
+EOF
+
+  exec "${0##*/}-nix-setup"
+fi
+
 version=$(solc --version)
 if grep -q 0.4.9 <<<"$version"; then
   echo >&2 "${0##*/}: error: solc 0.4.9 not supported"
